"""
Git Intelligence — автоматический commit после успешных изменений.
"""

import subprocess
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent


class GitIntelligence:
    def __init__(self):
        self.root = PROJECT_ROOT

    def has_changes(self) -> bool:
        """Проверить, есть ли изменения в репозитории."""
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=self.root,
            capture_output=True,
            text=True,
        )
        return bool(result.stdout.strip())

    def get_diff(self) -> str:
        """Получить diff изменений."""
        result = subprocess.run(
            ["git", "diff", "--stat"], cwd=self.root, capture_output=True, text=True
        )
        return result.stdout

    def generate_commit_message(self, task_title: str, task_id: str = None) -> str:
        """Сгенерировать сообщение для commit'а."""
        date = datetime.now().strftime("%Y-%m-%d %H:%M")
        msg = f"[Atlas] {task_title}\n\n"
        msg += f"Date: {date}\n"
        if task_id:
            msg += f"Task: {task_id}\n"
        msg += "Status: auto-commit\n"
        msg += f"Changes: {self.get_diff()[:200]}\n"
        msg += "\n---\nAuto-generated by Atlas Evolution Engine"
        return msg

    def commit(self, task_title: str, task_id: str = None) -> dict:
        """Выполнить commit, если есть изменения."""
        if not self.has_changes():
            return {"status": "no_changes", "message": "Нет изменений для commit'а"}

        msg = self.generate_commit_message(task_title, task_id)

        result = subprocess.run(
            ["git", "add", "-A"], cwd=self.root, capture_output=True, text=True
        )
        if result.returncode != 0:
            return {"status": "error", "message": f"Git add failed: {result.stderr}"}

        result = subprocess.run(
            ["git", "commit", "-m", msg], cwd=self.root, capture_output=True, text=True
        )
        if result.returncode != 0:
            return {"status": "error", "message": f"Git commit failed: {result.stderr}"}

        commit_hash = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=self.root,
            capture_output=True,
            text=True,
        ).stdout.strip()

        return {
            "status": "success",
            "commit": commit_hash,
            "message": f"✅ Commit {commit_hash}: {task_title}",
        }


if __name__ == "__main__":
    gi = GitIntelligence()
    print("Git Intelligence готов")
    print(f"Есть изменения: {gi.has_changes()}")